-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
SELECT '<Start Script>' AS ' ';
-- -----------------------------------------------------

-- -----------------------------------------------------
SELECT '<DROP DATABASE `transactionlogger_dev`>' AS ' ';
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `transactionlogger_dev`;

-- -----------------------------------------------------
SELECT '<CREATE DATABASE `transactionlogger_dev`>' AS ' ';
-- -----------------------------------------------------
CREATE DATABASE `transactionlogger_dev`;
USE transactionlogger_dev;



-- -----------------------------------------------------
SELECT '<Table `SEQUENCE GENERATOR`>' AS ' '; 
-- -----------------------------------------------------
delimiter //
create function seq_generator_fetch(seq_name char (20), inc_value int) returns BIGINT(20)
begin
 update seq_generator set val=last_insert_id(val+inc_value) where name=seq_name;
 return last_insert_id();
end
//
delimiter ;


CREATE TABLE `seq_generator` (
  `name` varchar(20) NOT NULL,
  `val` BIGINT(20) NOT NULL,
  PRIMARY KEY  (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
 
insert into seq_generator values('seq_gen_1',1); 




-- -----------------------------------------------------
SELECT '<Table `LogMessage`>' AS ' '; 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessage` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `APPLICATIONNAME` VARCHAR(255) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `FLOWNAME` VARCHAR(255) NULL DEFAULT NULL,
  `FLOWPOINTNAME` VARCHAR(255) NULL DEFAULT NULL,
  `ISERROR` TINYINT(1) NULL DEFAULT '0',
  `TRANSACTIONREFERENCEID` VARCHAR(255) NULL DEFAULT NULL,
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY(`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessage.PARTITION_ID` (`PARTITION_ID` ASC),
  INDEX `idx_LogMessage.APPLICATIONNAME` (`APPLICATIONNAME` DESC),
  INDEX `idx_LogMessage.EXPIREDDATE` (`EXPIREDDATE` ASC),
  INDEX `idx_LogMessage.FLOWNAME` (`FLOWNAME` DESC),
  INDEX `idx_LogMessage.TRANSACTIONREFERENCEID` (`TRANSACTIONREFERENCEID` DESC),
  INDEX `idx_LogMessage.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ SLOW DISK
-- INDEX DIRECTORY = ’/AbsolutePath/’ FAST DISK
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_01`>' AS ' '; 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_01` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(20) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_01.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_01.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_01.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_01.EXPIREDDATE` (`EXPIREDDATE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;


 
-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_02`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_02` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(40) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_02.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_02.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_02.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_02.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;


   
    
-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_03`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_03` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(60) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_03.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_03.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_03.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_03.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;


-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_04`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_04` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(80) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_04.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_04.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_04.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_04.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;

 

-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_05`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_05` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(100) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_05.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_05.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_05.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_05.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;


 
   

-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_06`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_06` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(150) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_06.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_06.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_06.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_06.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_07`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_07` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` VARCHAR(200) NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_07.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_07.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_07.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_07.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_08`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_08` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` TINYTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_08.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_08.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_08.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_08.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;

 
 
-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_09`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_09` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` TEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_09.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_09.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_09.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_09.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_10`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_10` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_10.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_10.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_10.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_10.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;


-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_11`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_11` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_11.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_11.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_11.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_11.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;




-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_12`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_12` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_12.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_12.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_12.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_12.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;




-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_13`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_13` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_13.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_13.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_13.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_13.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;




-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_14`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_14` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_14.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_14.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_14.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_14.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_15`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_15` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_15.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_15.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_15.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_15.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_16`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_16` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` MEDIUMTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_16.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_16.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_16.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_16.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;



-- -----------------------------------------------------
SELECT '<Table `LogMessageData_Partition_17`>' AS ' ';
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogMessageData_Partition_17` (
  `ID` BIGINT(20) NOT NULL,
  `PARTITION_ID` INT NOT NULL,
  `CONTENT` LONGTEXT NULL DEFAULT NULL,
  `CONTENTSIZE` BIGINT(20) NULL DEFAULT NULL,
  `LABEL` VARCHAR(255) NULL DEFAULT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `MODIFIED` TINYINT(1) NULL DEFAULT '0',
  `SEARCHABLE` TINYINT(1) NULL DEFAULT '0',
  `UTCLOCALTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `UTCSERVERTIMESTAMP` DATETIME(6) NULL DEFAULT NULL,
  `EXPIREDDATE` DATE NULL DEFAULT NULL,
  `LOGMESSAGE_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`PARTITION_ID`),
  UNIQUE KEY (`ID`,`PARTITION_ID`),
  INDEX `idx_LogMessageData_Partition_17.PARTITION_ID`(`PARTITION_ID` ASC),
  INDEX `idx_LogMessageData_Partition_17.LOGMESSAGE_ID` (`LOGMESSAGE_ID` DESC),
  INDEX `idx_LogMessageData_Partition_17.UTCSERVERTIMESTAMP` (`UTCSERVERTIMESTAMP` DESC),
  INDEX `idx_LogMessageData_Partition_17.EXPIREDDATE` (`EXPIREDDATE` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
-- DATA DIRECTORY  = ’/AbsolutePath/’ 
-- INDEX DIRECTORY = ’/AbsolutePath/’
PARTITION BY HASH(`PARTITION_ID`)
PARTITIONS 732;

 -- -----------------------------------------------------
SELECT '<END Script>' AS ' ';
-- -----------------------------------------------------
